# Generated by Django 5.2.3 on 2025-06-29 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subdomain', models.CharField(max_length=255)),
                ('domain', models.CharField(choices=[('makeshuman.art', 'makeshuman.art'), ('writingstudio.org', 'writingstudio.org')], default='makeshuman.art', max_length=255)),
                ('theme', models.CharField(choices=[('hugo-paper', 'Paper')], default='hugo-paper', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='site',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='editor.site'),
            preserve_default=False,
        ),
    ]
