# Generated by Django 5.2.3 on 2025-06-29 21:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_site_page_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='page',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='index',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date modified'),
        ),
    ]
